import Link from 'next/link';
import { notFound } from 'next/navigation';
import { byPath, guides, templates, trust } from '@/src/lib/content';
const extra:{[k:string]:string}={
'/about/':'Print Ready Tools provides free browser-based calculators for print sizes, DPI, bleed, safe zones, KDP paperback setup and Etsy printable files. We are independent and not affiliated with Amazon, Etsy, Canva or Adobe.',
'/contact/':'Contact: replace contact@example.com with your production support email before final launch. Send corrections, source updates and feature requests.',
'/privacy/':'Images are checked locally in your browser and are not uploaded or stored. Analytics should only use anonymous aggregate events and never record file names or exact image content.',
'/terms/':'These tools are provided as-is for general print setup guidance. Verify final requirements with your printer, marketplace or publisher.',
'/disclaimer/':'This site does not guarantee KDP, Etsy or print approval. Official templates and printer specifications override calculator estimates.',
'/glossary/':'DPI/PPI: pixels per inch for print sizing. Bleed: extra artwork beyond trim. Safe zone: area inside trim for important content. Trim: final cut size. Aspect ratio: width-to-height proportion.',
'/templates/etsy-buyer-instruction-template/':'Thank you for purchasing this printable. Choose the ratio file matching your frame, print at 100% scale, and use high-quality paper or a professional print shop. Files are for personal use only unless your listing says otherwise.',
'/templates/kdp-cover-setup-checklist/':'KDP cover checklist: calculate trim, spine and bleed; create one PDF with back cover, spine and front cover; keep text in the safe zone; leave barcode space; verify with the official KDP previewer.',
'/templates/print-ready-pdf-checklist/':'Print-ready PDF checklist: correct page size, required bleed, embedded fonts, high-resolution images, safe-zone content, correct color profile, and printer-specific export settings.'
};
export function generateStaticParams(){return [...guides,...templates,...trust].map(([href])=>({slug:href.split('/').filter(Boolean)}))}
export function generateMetadata({params}:{params:{slug:string[]}}){const path='/' + params.slug.join('/') + '/';const item=byPath(path);return {title:item?.[1]||'Print Ready Guide',description:item?.[2]||'Print-ready calculator guide and checklist.'}}
export default function Page({params}:{params:{slug:string[]}}){const path='/' + params.slug.join('/') + '/';const item=byPath(path);if(!item)notFound();const [href,title,desc]=item;const body=extra[path]||`${desc} Use the related calculator to enter your own values, review formulas, copy results, and download guide templates. This page explains when the result applies, when it does not, and what official platform checks still matter.`;return <main className="container stack"><article className="card"><h1>{title}</h1><p>{body}</p><h2>Formula or rule</h2><p>Use physical size × DPI for pixel requirements. For bleed, add bleed to both sides. For KDP covers, use back cover + spine + front cover + outside bleed.</p><h2>Worked example</h2><p>At 300 DPI, an 8 × 10 inch print needs 2400 × 3000 pixels. A 6 × 9 inch KDP interior with bleed becomes 6.125 × 9.25 inches.</p><h2>Limits</h2><p>Printer, paper, marketplace and software requirements vary. Use official platform templates as the final check.</p><h2>Related calculators</h2><p><Link href="/print-size-calculator/">Print Size Calculator</Link> · <Link href="/bleed-safe-zone-calculator/">Bleed & Safe Zone Calculator</Link> · <Link href="/kdp-cover-calculator/">KDP Cover Size Calculator</Link> · <Link href="/etsy-printable-size-calculator/">Etsy Printable Size Pack Calculator</Link></p><p className="small muted">Sources and last updated: KDP, Etsy and common print production guidance. Last updated 2026-05-22.</p></article></main>}
